### ISSUE TITLE
Release 0.16.0 checklist

### ISSUE THREAD

**Issue by tbombach** [Azure/autorest#1027]
# Releasing AutoRest and ClientRuntimes

 - [x] Merge pending PRs into the master branch
 - [x] Create a release-0.16.0 branch from master
 - [x] Update Changelog.md
 - [x] Publish .NET Runtimes (increment versions as appropriate) using [automated build](http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-publish/)
 - [x] Publish Node Runtimes (increment versions as appropriate)
 - [ ] ~~Publish Java Runtimes (increment versions as appropriate)~~
 - [ ] ~~Publish Ruby Runtimes (increment versions as appropriate)~~
 - [ ] ~~Publish Python Runtimes (increment versions as appropriate)~~
 - [x] Create a signed package using [automated build](http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign/) with build parameters: sha1: release branch name, scope: CodeGenerator
 - [x] Smoke Test the signed package (Run Autorest.exe to check help and generate a sample spec for any language)
 - [x] Publish Choco package {upload autorest.0.16.0.symbols.nupkg from the downloaded archive of the successful signing job}(Please look at the secure notebook for creds) 
 - [x] Publish nuget package  [using automated build](http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-publish/) with build parameters: sha1: release branch name, scope: CodeGenerator, tag: AutoRest-0.16.0
 - [x] Create a draft github release from the release branch including a tag (se the one created by the publish nuget package step)
    - Mark the release as pre-release if applicable
 - [x] Add -SNAPSHOT to Java Runtime versions
 - [x] Update [Docker file](https://github.com/Azure/autorest/blob/master/Tools/dockerfiles/Dockerfile) in the release branch   
 - [x] Add zip packages as a binary to the release
 - [x] Copy over the changelog as release notes for github release
 - [x] Publish the github release
-  [x] login to [dockerhub] (https://hub.docker.com/r/azuresdk/autorest/~/settings/automated-builds/) and trigger the build using the release tag
 - [x] Smoke test the nuget and npm packages
 - [x] Merge release -> master
 - [x] Bump up the version of autorest.exe
      - [x] Update Assembly Info in AutoRest.Core
      - [x] Update AutoRest.nuget.proj to build nightly using the next version
      - [x] Update NugetPackageTest/packages.config to use the new version of AutoRest
      - [x] Run `gulp syncDependencies` from the root of the cloned AutoRest repository
