### ISSUE TITLE
Testing and Code quality of autorest

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/autorest#3941]
Epic tracking improvements to the testing story of autorest

- [x] Migrate all project to `jest` 
- [x] Update regression tests to consume packed packages instead of local source(Validates that the build and packed package is working)
- [x] Cross node version testing(All supported LTS node versions(`10`, `12`, `14`)
- [x] Smoke tests from csharp
- [x] Investigate adding some regression tests for configuration loading(Using jest snapshot maybe)
- [x] Add code coverage reporting
- [x] Add jest eslint rules to prevent comiting `fit`
