### ISSUE TITLE
autorest.core (January-June 2021)

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#3995]
Features:
- [x] OpenAPI3 discriminator `mapping` support #3956
- [x] New OpenAPI 3.0 output flag #3975
- [x] Credential standardization #3718
- [ ] Various [P1 issues](https://github.com/Azure/autorest/issues?q=is%3Aopen+is%3Aissue+label%3A%22P1+-+Required%22)
  - [x] Duplicate operations #3653
- [x] Sourcemap for better error #4025 
- [x] `--stats` flag to generate some statistics #4023 

Reliability:
- [x] unhandled promises causing silent crashes #3965 
- [x] improved logging system #3988
- [ ] testing improvements #3861
