### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/autorest#4224]
Using msgraph spec for benchmark as every plugin take a long time

Plugins:
- [x] Components-cleaner #4228
- [x] Quickcheck plugin #4225
- [x] Allof cleaner plugin #4238
- [x] Merger plugin #4239
- [x] Yaml Parsing extremly slow for large specs in between plugins #4235
- [x] Remove linq libary completely (#4240, #4241)
- [x] New sourcemap system. Remove need for ast parsing wich has terrible perf for large specs #4243
