### ISSUE TITLE
Pass compilation for all the test projects

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest#4947]
Currently the generated typespec in tests projects cannot compile. We should at least make all the green field and DPG projects pass the compilation.

```[tasklist]
### Tasks
- [x] Add the compilation command: https://github.com/Azure/autorest/pull/4948
- [ ] https://github.com/Azure/autorest/issues/4949
- [ ] https://github.com/Azure/autorest/issues/4950
- [ ] https://github.com/Azure/autorest/issues/4951
- [ ] https://github.com/Azure/autorest/issues/4953
- [ ] https://github.com/Azure/autorest/issues/4955
- [ ] https://github.com/Azure/autorest/issues/4957
- [ ] https://github.com/Azure/autorest/issues/4959
- [ ] https://github.com/Azure/typespec-azure/issues/57
```

All the projects we need to enable:
- [ ] analyzeText
- [x] anomalyDetector
- [x] arm-agrifood
- [ ] arm-alertsmanagement
- [ ] arm-analysisservices
- [ ] arm-apimanagement
- [ ] arm-authorization
- [ ] arm-azureintegrationspaces
- [ ] arm-compute
- [ ] arm-dns
- [ ] arm-machinelearningservices
- [x] arm-networkanalytics
- [x] arm-playwrighttesting
- [x] arm-servicenetworking
- [x] arm-sphere
- [x] arm-storage
- [x] arm-test
- [ ] batch
- [ ] bodyComplex
- [ ] complexObject
- [ ] confidentialLedger
- [ ] keyvault
- [ ] loadTest
- [ ] nh
- [ ] openAI
- [ ] pagination
- [ ] qna
- [ ] qnaAuthoring
- [ ] qnaRuntime
- [ ] schemaRegistry
- [ ] url
- [ ] utils
- [ ] webpubsub
