### ISSUE TITLE
Release-0.15.0 checklist

### ISSUE THREAD

**Issue by amarzavery** [Azure/autorest#802]
# Releasing AutoRest and ClientRuntimes

 - [x] Merge pending PRs into the master branch
 - [x] Create a release branch from master
 - [x] Update Changelog.md
 - [x] Publish .NET Runtimes (increment versions as appropriate) using [automated build](http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-publish/)
 - [x] Publish Node Runtimes (increment versions as appropriate)
 - [x] Publish Java Runtimes (increment versions as appropriate)
 - [x] Publish Ruby Runtimes (increment versions as appropriate)
 - [x] Publish Python Runtimes (increment versions as appropriate)
 - [x] Create a signed package using [automated build](http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-sign/) with build parameters: sha1: release branch name, scope: CodeGenerator
 - [x] Smoke Test the signed package (Run Autorest.exe to check help and generate a sample spec for any language)
 - [x] Publish Choco package (Please look at the secure notebook for creds)
 - [x] Publish nuget package  [using automated build](http://azuresdkci.cloudapp.net/view/3-AutoRest/job/autorest-publish/)
 - [x] Create a github release from the release branch including a tag
 - [x] Add -SNAPSHOT to Java Runtime versions
 - [x] Update [Docker file](https://github.com/Azure/autorest/blob/master/Tools/dockerfiles/Dockerfile) in the release branch   
 - [x] Add zip packages as a binary to the release
 - [x] Copy over the changelog as release notes for github release
 - [x] Publish the github release
-  [x] login to [dockerhub] (https://hub.docker.com/r/azuresdk/autorest/~/settings/automated-builds/) and trigger the build using the release tag
 - [x] Smoke test the nuget and npm packages
 - [x] Merge release -> master
 - [x] Bump up the version of autorest.exe
      - [x] Update Assembly Info in AutoRest.Core
      - [x] Update AutoRest.nuget.proj to build nightly using the next version
      - [x] Run `gulp syncDependencies` from the root of the cloned AutoRest repository
